name: Hantar Web ke Neocities Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil kod repo terkini
      uses: actions/checkout@v4

    - name: Tembak fail masuk Neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        # PENTING: Kita beritahu robot, fail kita ada dekat luar sekali (root directory)
        dist_dir: _site
        cleanup: true